#!/usr/bin/env bash

# Retrieve domain name information.
# 	Usage: domain_info domain subdomains
# 	Example 1: domain_info google.com www
# 	Example 2: domain_info google.com 'www photos maps mail'
domain_info() {
	domain="$1"
	subdomains=()
	readarray -t subdomains < <(echo "$2" | tr ' ' '\n')
	for ((i = 0; i < "${#subdomains[@]}"; i++)) do
		subdomain="${subdomains[i]}"
		output_awk='{print "The subdomain", "'
		output_awk="$output_awk$subdomain is a"
		output_awk="$output_awk\", \$7, \"record and points to\", \$8}"
		dig "$subdomain.$domain" \
			| grep -A1 'ANSWER SECTION:' \
			| tr '\n' ' ' \
			| awk "$output_awk"
	done
}

if [ "${#BASH_ARGV[@]}" -ge '2' ]; then
	domain_info "$1" "$2"
elif [ "${#BASH_ARGV[@]}" -ge '1' ]; then
	domain_info "$1" "www lb-01 web-01 web-02"
else
	exit
fi
