#!/usr/bin/env bash

# Retrieve domain name information.
domain_info () {
 if [ "$#" -ge 2 ]
 then
  subdomain="$2.$1"
  record=$(dig "$subdomain" | grep -A1 'ANSWER SECTION:' | awk '{print$4}')
  ip=$(dig "$subdomain" | grep -A1 'ANSWER SECTION:' | awk '{print$5}')
  echo "The subdomain $2 is a"$record" record and points to"$ip""
 else
  declare -a subdomains=("www" "lb-01" "web-01" "web-02")
  for x in "${subdomains[@]}"; do
   subdomain="$x.$1"
   record=$(dig "$subdomain" | grep -A1 'ANSWER SECTION:' | awk '{print$4}')
   ip=$(dig "$subdomain" | grep -A1 'ANSWER SECTION:' | awk '{print$5}')
   echo "The subdomain $x is a"$record" record and points to"$ip""
 done 
 fi
}

if [ "$#" -ge 2 ]
 then
 domain_info $1 $2
else
 domain_info $1
fi
