#!/usr/bin/env bash
# script installs nginx, then configures it and starts nginx on a remote server

apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
service nginx start
