#!/usr/bin/env bash
# script installs nginx, then configures it and starts nginx on a remote server

apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World' > /var/www/html/index.nginx-debian.html
service nginx start
