#!/usr/bin/env bash
# Bash script to correct what is wrong with the server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx start
