#!/usr/bin/env bash
# a script that displays 1 to 100, FizzBuzz if divisible by 3 and 5, Fizz if divisible by 3, Buzz if divisible by 5, otherwise the number.

i=1
while [ $i -lt 101 ]
do
    if [ $((i%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((i%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    let i+=1
done
