#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 and displays a message based off certain conditions.

INDEX=1
while [ $INDEX -lt 11 ]
do
    if [ $INDEX = 4 ]
    then
        echo "bad luck"
    elif [ $INDEX = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    let INDEX+=1
done
